name: Android Emulator Screenshot

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-emulator-screenshot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Download Android SDK Tools
        uses: android-actions/setup-android@v3

      - name: Install Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build Debug APK
        run: |
         cd java/android_/MySingleFileApp
         gradle :app:assembleDebug

      - name: Start Android Emulator and Take Screenshot
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: google_apis
          arch: x86_64
          profile: Nexus 6
          script: |
            cd java/android_/MySingleFileApp
            adb install -r app/build/outputs/apk/debug/app-debug.apk
            adb shell am start -n com.example.singlefilexml/.MainActivity
            sleep 10 # wait for the UI to load
            adb exec-out screencap -p > screenshot.png

      - name: Upload Emulator Screenshot
        uses: actions/upload-artifact@v4
        with:
          name: emulator-screenshot
          path: |
           java/android_/MySingleFileApp/screenshot.png