name: Build and Run Assembly Code

on:
  push:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install NASM
      run: sudo apt-get update && sudo apt-get install -y nasm

    - name: Assemble the code, Link the object file, Run the program
      run: |
        #!/bin/bash
        cd assembly_

        # Compile all .asm files into .o files
        for file in *.asm; do
            if [[ -f "$file" ]]; then  # Only process regular files
                echo "Compiling $file..."
                nasm -f elf32 -o "${file%.asm}.o" "$file"
            fi
        done

        # Link all .o files into a single executable (optional: adjust as needed)
        echo "Linking object files into the executable..."
        ld -m elf_i386 -o my_program *.o

        # Check if the executable exists and run it
        if [[ -f my_program && -x my_program ]]; then
            echo "Running the program..."
            ./my_program
        else
            echo "Error: Executable 'my_program' not found or is not executable."
        fi



