name: Build and Run Assembly Code

on:
  push:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install NASM
      run: sudo apt-get update && sudo apt-get install -y nasm gcc

    - name: Assemble the code, Link the object file, Run the program
      run: |
        #!/bin/bash
        cd assembly_

        nasm -f elf64 hello.asm -o hello.o
        ld hello.o -o hello
        ./hello

        nasm -f elf64 -o program.o program.s
        gcc -no-pie -o program program.o
        ./program

        cd ..

    - name: Assemble the code, Link the object file, Run the program again
      run: |
        #!/bin/bash
        cd assembly_

        for asm_file in *.asm; do
            # Check if the file exists
            if [ -f "$asm_file" ]; then
                echo "Assembling and running $asm_file..."

                # Get the file name without the extension
                filename=$(basename -- "$asm_file")
                filename_noext="${filename%.*}"

                # Assemble the file using NASM (assuming it's x86-64, adjust for other architectures)
                nasm -f elf64 "$asm_file" -o "$filename_noext.o"
                
                # Link the object file to create an executable
                ld "$filename_noext.o" -o "$filename_noext"

                # Run the resulting executable
                ./"$filename_noext"

                # Clean up the object and executable files after running
                rm "$filename_noext.o" "$filename_noext"
            fi
        done



