name: Build and Run Assembly Code

on:
  push:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install NASM
      run: sudo apt-get update && sudo apt-get install -y nasm

    - name: Assemble the code, Link the object file, Run the program
      run: |
       cd assembly_

        # Compile all .asm files into .o files
        for file in *.asm; do
            echo "Compiling $file..."
            nasm -f elf32 -o "${file%.asm}.o" "$file"
        done

        # Link all .o files into executables
        for obj in *.o; do
            echo "Linking $obj..."
            ld -m elf_i386 -o "${obj%.o}" "$obj"
        done

        # Run all executables
        for exe in *; do
            if [[ -x "$exe" && ! "$exe" =~ \. ]]; then
                echo "Running $exe:"
                ./"$exe"
                echo ""
            fi
        done


