name: Render CAD Diagram

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y openscad mesa-utils libgl1-mesa-dri xvfb

    - name: Render CAD Diagram
      run: |
        # Set up environment variables for software rendering
        export DISPLAY=:99
        export LIBGL_ALWAYS_SOFTWARE=1
        export MESA_GL_VERSION_OVERRIDE=3.3
        export MESA_GLSL_VERSION_OVERRIDE=330

        # Start a virtual X server
        Xvfb :99 -screen 0 1024x768x24 &

        cd cad
        mkdir -p cad_output
        openscad -o cad_output/example.png example.scad
        openscad -o cad_output/example1.png example1.scad
        openscad -o cad_output/example2.png example2.scad

    - name: Upload rendered diagram
      uses: actions/upload-artifact@v4
      with:
        name: cad-diagram
        path: cad/cad_output