name: Cassandra DB Setup and Test

on:
  push:
    branches:
      - main

jobs:
  cassandra_setup:
    runs-on: ubuntu-latest
    services:
      cassandra:
        image: cassandra:3.11  # Using Cassandra 4.0 Docker image
        ports:
          - 9042:9042  # Exposing port for Cassandra CQL
        # options: >-
        #   --health-cmd="cqlsh -e 'DESCRIBE KEYSPACES'"
        #   --health-interval=10s
        #   --health-timeout=5s
        #   --health-retries=3
        #   --memory=4g
        #   --cpus=2

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install cqlsh
        run: |
          echo "Installing cqlsh..."
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install cassandra-driver
          wget https://downloads.apache.org/cassandra/tools/cqlsh-astra/cqlsh-astra-20230517.tar.gz
          tar -xvzf cqlsh-astra-20230517.tar.gz
          sudo mv cqlsh-astra/bin/cqlsh /usr/local/bin/cqlsh
          sudo chmod +x /usr/local/bin/cqlsh

      # Step 2: Wait for Cassandra to be ready
      - name: Wait for Cassandra to be ready
        run: |
          echo "Waiting for Cassandra to be ready..."
          until cqlsh -u cassandra -e "DESCRIBE KEYSPACES"; do
            echo "Waiting for Cassandra to start..."
            sleep 5
          done
          echo "Cassandra is ready."

      # Step 3: Setup Cassandra schema (keyspace, table) using a shell script
      - name: Setup Cassandra Schema
        run: |
          echo "Creating keyspace and table..."
          cqlsh -u cassandra -e "
            CREATE KEYSPACE IF NOT EXISTS test_keyspace 
            WITH replication = {'class': 'SimpleStrategy', 'replication_factor': 1};
            USE test_keyspace;
            CREATE TABLE IF NOT EXISTS users (
              id UUID PRIMARY KEY,
              name TEXT,
              email TEXT
            );
          "
          echo "Keyspace and table created."

      # Step 4: Insert some test data
      - name: Insert Test Data into Cassandra
        run: |
          echo "Inserting test data into Cassandra..."
          cqlsh -u cassandra -e "
            USE test_keyspace;
            INSERT INTO users (id, name, email) VALUES (uuid(), 'John Doe', 'john@example.com');
            INSERT INTO users (id, name, email) VALUES (uuid(), 'Jane Smith', 'jane@example.com');
          "
          echo "Test data inserted."

      # Step 5: Query Cassandra to verify data
      - name: Query Cassandra
        run: |
          echo "Querying Cassandra for inserted data..."
          cqlsh -u cassandra -e "
            USE test_keyspace;
            SELECT * FROM users;
          "
