name: Cassandra Setup on macOS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup-cassandra:
    runs-on: macos-latest  # Specify macOS as the runner

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Install Homebrew (if not installed)
      run: |
        if ! command -v brew &> /dev/null
        then
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        fi
        brew update

    - name: Install Java
      run: |
        brew install openjdk@11
        echo 'export PATH="/opt/homebrew/opt/openjdk@11/bin:$PATH"' >> ~/.zshrc
        source ~/.zshrc
        java -version

    - name: Install Cassandra
      run: |
        brew tap homebrew/cask
        brew install cassandra

    - name: Start Cassandra
      run: |
        brew services start cassandra

    - name: Verify Cassandra is running
      run: |
        nodetool status
        sudo lsof -i :9042  # Check if Cassandra's default CQL port is open

    - name: Install Python and Cassandra CQLSH (Optional for testing)
      run: |
        brew install python
        curl -L https://github.com/python-driver/cassandra-driver/archive/refs/tags/3.25.0.tar.gz | tar xz
        cd cassandra-driver-3.25.0
        sudo python3 setup.py install

    - name: Connect to Cassandra with CQLSH
      run: |
        cqlsh -e "DESCRIBE KEYSPACES;"
        cqlsh -e "CREATE KEYSPACE IF NOT EXISTS test_keyspace WITH replication = {'class' : 'SimpleStrategy', 'replication_factor' : 1};"
        cqlsh -e "USE test_keyspace; CREATE TABLE IF NOT EXISTS users (id UUID PRIMARY KEY, name text, age int);"
        cqlsh -e "INSERT INTO test_keyspace.users (id, name, age) VALUES (uuid(), 'Alice', 30);"
        cqlsh -e "SELECT * FROM test_keyspace.users;"
