name: Cassandra Setup

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup-cassandra:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Update system and install Java
      run: |
        sudo apt update
        sudo apt upgrade -y
        sudo apt install openjdk-11-jdk -y
        java -version

    - name: Add Apache Cassandra repository
      run: |
        curl https://downloads.apache.org/cassandra/keys.asc | sudo apt-key add -
        echo "deb https://downloads.apache.org/cassandra/debian 311x main" | sudo tee -a /etc/apt/sources.list.d/cassandra.sources.list

    - name: Install Apache Cassandra
      run: |
        sudo apt update
        sudo apt install cassandra -y

    - name: Start Cassandra service
      run: |
        sudo systemctl start cassandra
        sudo systemctl enable cassandra

    - name: Verify Cassandra is running
      run: |
        sudo systemctl status cassandra
        nodetool status

    - name: Install Python and Cassandra CQLSH (for example to test)
      run: |
        sudo apt install python3 -y
        curl -L https://github.com/python-driver/cassandra-driver/archive/refs/tags/3.25.0.tar.gz | tar xz
        cd cassandra-driver-3.25.0
        sudo python3 setup.py install

    - name: Connect to Cassandra with CQLSH
      run: |
        cqlsh -e "DESCRIBE KEYSPACES;"
        cqlsh -e "CREATE KEYSPACE IF NOT EXISTS test_keyspace WITH replication = {'class' : 'SimpleStrategy', 'replication_factor' : 1};"
        cqlsh -e "USE test_keyspace; CREATE TABLE IF NOT EXISTS users (id UUID PRIMARY KEY, name text, age int);"
        cqlsh -e "INSERT INTO test_keyspace.users (id, name, age) VALUES (uuid(), 'Alice', 30);"
        cqlsh -e "SELECT * FROM test_keyspace.users;"
