name: Cassandra Example Workflow

on:
  push:
    branches:
      - main

jobs:
  cassandra-job:
    runs-on: ubuntu-latest

    services:
      cassandra:
        image: cassandra:4.0
        ports:
          - 9042:9042
        options: >-
          --health-cmd="cqlsh -e 'DESCRIBE KEYSPACES'"
          --health-interval=10s
          --health-timeout=25s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Wait for Cassandra to be ready
        run: |
          echo "Waiting for Cassandra to be ready..."
          for i in {1..30}; do
            if cqlsh -e "DESCRIBE KEYSPACES"; then
              echo "Cassandra is ready!"
              break
            fi
            echo "Waiting for Cassandra..."
            sleep 2
          done

      - name: Install Cassandra client
        run: sudo apt-get update && sudo apt-get install -y cassandra-cql

      - name: Create a keyspace and table, and insert data
        run: |
          echo "Connecting to Cassandra and creating a keyspace and table..."
          cqlsh -e "
          CREATE KEYSPACE IF NOT EXISTS sample_keyspace
          WITH replication = {'class': 'SimpleStrategy', 'replication_factor': 1};
          USE sample_keyspace;
          CREATE TABLE IF NOT EXISTS users (
            id UUID PRIMARY KEY,
            name TEXT,
            email TEXT
          );
          INSERT INTO users (id, name, email) VALUES (uuid(), 'John Doe', 'john.doe@example.com');
          INSERT INTO users (id, name, email) VALUES (uuid(), 'Jane Smith', 'jane.smith@example.com');
          "

      - name: Query the database
        run: |
          echo "Querying the database..."
          cqlsh -e "
          USE sample_keyspace;
          SELECT * FROM users;
          "
