name: Docker Workflow

on:
  push:
    branches:
      - main

jobs:
  build-and-run:
    name: Docker run workflow
    runs-on: ubuntu-latest

    steps:

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Application docker - 1
        working-directory: ./kotlin/spring_boot
        run: |
          docker build -t my-spring-app:latest .
          docker tag my-spring-app sreedockerhub19/my-spring-app:latest
          docker push sreedockerhub19/my-spring-app:latest

      - name: Build Application docker - 2
        working-directory: ./java/vertx_
        run: |
          docker build -t my-vertx-app .
          docker tag my-vertx-app sreedockerhub19/my-vertx-app:latest
          docker push sreedockerhub19/my-vertx-app:latest

      - name: Build Application docker - 3
        working-directory: ./kotlin/vertx_
        run: |
          docker build -t my-vertx-app-kotlin .
          docker tag my-vertx-app-kotlin sreedockerhub19/my-vertx-app-kotlin:latest
          docker push sreedockerhub19/my-vertx-app-kotlin:latest

      - name: Build Application docker - 4
        working-directory: ./kotlin/ktor_
        run: |
          docker build -t my-ktor-app .
          docker tag my-ktor-app sreedockerhub19/my-ktor-app:latest
          docker push sreedockerhub19/my-ktor-app:latest