name: Kafka Python CI

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      zookeeper:
        image: wurstmeister/zookeeper
        ports:
          - 2181:2181
      kafka:
        image: wurstmeister/kafka
        env:
          KAFKA_ADVERTISED_HOST_NAME: localhost
          KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
          KAFKA_ADVERTISED_PORT: 9092
          KAFKA_CREATE_TOPICS: "my-topic:1:1"
        ports:
          - 9092:9092
        options: >-
          --health-cmd "echo 'ok'" --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
            java-version: '21'
            distribution: 'temurin'

      - name: Set up Maven
        run: sudo apt-get install -y maven

      - name: Build
        run: |
            cd java/kafka_
            mvn clean compile

      - name: Wait for Kafka to be Ready
        run: |
            echo "Waiting for Kafka..."
            sleep 30

      - name: Run Producer
        run: |
         cd java/kafka_
         mvn exec:java -Dexec.mainClass="com.example.kafka.ProducerExample"

      - name: Run Consumer
        run: |
         cd java/kafka_
         mvn exec:java -Dexec.mainClass="com.example.kafka.ConsumerExample"

    #   - name: Install dependencies
    #     run: |
    #       python -m pip install --upgrade pip
    #       pip install -r requirements.txt

    #   - name: Run tests
    #     run: |
    #       pytest
