name: Kafka Java CI

on:
    push:
        branches:
          - main

jobs:
  kafka-test:
    runs-on: ubuntu-latest
    services:
      zookeeper:
        image: bitnami/zookeeper:3.8
        ports:
          - 2181:2181
        env:
          ALLOW_ANONYMOUS_LOGIN: yes

      kafka:
        image: bitnami/kafka:3.7
        ports:
          - 9092:9092
        env:
          KAFKA_BROKER_ID: 1
          KAFKA_CFG_ZOOKEEPER_CONNECT: localhost:2181
          KAFKA_CFG_LISTENERS: PLAINTEXT://:9092
          KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
          KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "true"
          ALLOW_PLAINTEXT_LISTENER: "yes"
        options: >-
          --health-cmd "kafka-topics.sh --bootstrap-server localhost:9092 --list || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Set up Maven
        run: sudo apt-get install -y maven

      - name: Build
        run: mvn clean compile

      - name: Wait for Kafka to be Ready
        run: |
          echo "Waiting for Kafka..."
          sleep 30

      - name: Run Producer
        run: mvn exec:java -Dexec.mainClass="com.example.kafka.ProducerExample"

      - name: Run Consumer
        run: mvn exec:java -Dexec.mainClass="com.example.kafka.ConsumerExample"
