name: Kafka Java CI

on: [push, pull_request]

jobs:
  kafka-test:
    runs-on: ubuntu-latest
    services:
      zookeeper:
        image: confluentinc/cp-zookeeper:7.5.0
        ports:
          - 2181:2181
        options: >-
          --health-cmd "echo ruok | nc localhost 2181 || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      kafka:
        image: confluentinc/cp-kafka:7.5.0
        ports:
          - 9092:9092
        env:
          KAFKA_BROKER_ID: 1
          KAFKA_ZOOKEEPER_CONNECT: localhost:2181
          KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
          KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
          KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        options: >-
          --health-cmd "kafka-topics --bootstrap-server localhost:9092 --list || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      - name: Build project
        run: |
         cd java/kafka_
         mvn clean compile

      - name: Create Kafka topic
        run: |
          sleep 10
          cd java/kafka_
          kafka-topics --create --topic test-topic --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1

      - name: Run Producer
        run: |
         cd java/kafka_
         mvn exec:java -Dexec.mainClass="com.example.kafka.ProducerExample"

      - name: Run Consumer
        run: |
         cd java/kafka_
         mvn exec:java -Dexec.mainClass="com.example.kafka.ConsumerExample"
