name: Git submodules sync

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H github.com >> ~/.ssh/known_hosts

      - name: Checkout code with submodules
        uses: actions/checkout@v2
        with:
          submodules: true
          token: ${{ secrets.CI_TOKEN }}  # Your PAT secret


      - name: Run Git submodules sync
        env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "cpadmaja2003@gmail.com"
          git config --global user.name "sreegithub19"
          git config --global pull.rebase false


          #git submodule foreach --recursive 'git pull origin HEAD --allow-unrelated-histories'
          cd CPP/codeforces_script && git fetch && git checkout cpp_ && git pull origin cpp_ --allow-unrelated-histories

          git add .

          if [[ $(git diff --cached --quiet; echo $?) -ne 0 ]]; then
            git commit -m "Your commit message"
            git push origin main
          else
            echo "No changes to commit."
          fi