name: Build WebAssembly

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: |
       cd typescript/webassembly_/assembly_Script
       npm install --save-dev assemblyscript && npm install
       npm install serve@14.2.4
       npm run asbuild
       npm start
       sleep 5
       #curl http://localhost:3000 -o index.html
       cd .. && cd .. && cd ..

       cd typescript/webassembly_/2d_game_
       npm install
       npm run asbuild:optimized -- --memoryBase 40000
       npx ws -p 1234 &
       sleep 10
       cd .. && cd .. && cd ..

    # - name: Upload WASM artifact
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: wasm
    #     path: |
    #      typescript/webassembly_/assembly_Script/index.html

    - name: Install Playwright
      run: |
        npm install playwright  # Install Playwright
        npx playwright install

    - name: Capture screenshot using Playwright
      run: |
        node -e "
        const fs = require('fs');
        const path = require('path');

        (async () => {
          const browser = await firefox.launch();
          const context = await browser.newContext({
            recordVideo: { dir: './videos', size: { width: 1280, height: 720 } },
          });
          const page = await context.newPage();

          await page.goto('http://localhost:3000');
          await page.screenshot({ path: 'screenshot_assembly_Script.png' });

          await page.goto('http://localhost:1234');
          await page.waitForTimeout(10000);
          await page.screenshot({ path: 'screenshot_2d_game.png' });

          await context.close();
          await browser.close();

          // Rename the video file
          const videoDir = './videos';
          const videoFile = fs.readdirSync(videoDir).find(file => file.endsWith('.webm'));
          if (videoFile) {
            fs.renameSync(path.join(videoDir, videoFile), path.join(videoDir, '2d_game_video.webm'));
            console.log('Video saved as 2d_game_video.webm');
          }
        })();

        "

    - name: Upload screenshot as artifact
      uses: actions/upload-artifact@v4
      with:
        name: screenshots
        path: |
         screenshot_assembly_Script.png
         screenshot_2d_game.png
         ./videos
