name: Build WebAssembly

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: |
       cd typescript/webassembly_/assembly_Script
       npm install --save-dev assemblyscript && npm install
       npm install serve@14.2.4
       npm run asbuild
       npm start
       sleep 5
       curl -O http://localhost:3000/index.html
       curl -O http://localhost:3000/hello-world.wasm

    - name: Upload WASM artifact
      uses: actions/upload-artifact@v4
      with:
        name: wasm
        path: |
         typescript/webassembly_/assembly_Script/index.html
         typescript/webassembly_/assembly_Script/hello-world.wasm
