name: Git submodules sync

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H github.com >> ~/.ssh/known_hosts

      - name: Checkout code with submodules
        uses: actions/checkout@v2
        with:
          submodules: true
          token: ${{ secrets.CI_TOKEN }}  # Your PAT secret

      - name: Initialize and update submodules
        run: git submodule update --init --recursive


      - name: Run Git submodules sync
        run: |
          git pull origin main 
          git submodule update --init --force --recursive 
          git config --global user.email "cpadmaja2003@gmail.com"
          git config --global user.name "sreegithub19"
          git add . 

          if [[ $(git diff --cached --quiet; echo $?) -ne 0 ]]; then
            git commit -m "Your commit message"
            git push origin main
          else
            echo "No changes to commit."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}