name: Build WebAssembly

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: |
       cd typescript/webassembly_/assembly_Script
       npm install --save-dev assemblyscript && npm install
       npm install serve@14.2.4
       npm run asbuild
       npm start
       sleep 5
       #curl http://localhost:3000 -o index.html
       cd .. && cd .. && cd ..

    # - name: Upload WASM artifact
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: wasm
    #     path: |
    #      typescript/webassembly_/assembly_Script/index.html

    - name: Install Playwright
      run: |
        npm install playwright  # Install Playwright
        npx playwright install

    - name: Capture screenshot using Playwright
      run: |
        node -e "
        const { firefox } = require('playwright');
        (async () => {
          const browser = await firefox.launch();  // You can use 'chromium', 'firefox', or 'webkit'
          const page = await browser.newPage();
          await page.goto('http://localhost:3000');  // Navigate to localhost
          await page.screenshot({ path: 'screenshot.png' });  // Capture screenshot
          await browser.close();
        })();
        "

    - name: Upload screenshot as artifact
      uses: actions/upload-artifact@v4
      with:
        name: screenshot
        path: screenshot.png  # Upload the screenshot
