name: MariaDB Example Workflow

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mariadb:
        image: mariadb:latest
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: testdb
          MYSQL_USER: testuser
          MYSQL_PASSWORD: testpass
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost -uroot -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    steps:
      - name: Show running containers
        run: docker ps

      - name: Wait for MariaDB to initialize
        run: |
          echo "Sleeping for 30s to allow MariaDB to start..."
          sleep 30

      - name: Run SQL commands in MariaDB
        run: |
          docker exec -i ${{ job.services.mariadb.id }} \
          mysql -uroot -proot testdb <<'EOF'
          CREATE TABLE IF NOT EXISTS users (
            id INT AUTO_INCREMENT PRIMARY KEY,
            name VARCHAR(50),
            age INT
          );
          INSERT INTO users (name, age) VALUES ('Alice', 30);
          INSERT INTO users (name, age) VALUES ('Bob', 25);
          SELECT * FROM users;
          EOF

      - name: Run SQL commands in MariaDB again
        run: |
          docker exec -i ${{ job.services.mariadb.id }} \
          mysql -uroot -proot testdb <<'EOF'
          -- Use sys.exec for multiline SQL execution
          CALL sys.exec('
              CREATE TABLE IF NOT EXISTS users (
                  id INT AUTO_INCREMENT PRIMARY KEY,
                  name VARCHAR(50),
                  age INT
              );

              INSERT INTO users (name, age) VALUES (''Alice'', 40);
              INSERT INTO users (name, age) VALUES (''Bob'', 35);
          ');

          -- Verify the inserted data
          SELECT * FROM users;
          EOF