name: MySQL Workflow

on:
  push:
    branches:
      - main

jobs:
  test-mysql:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
        env:
          MYSQL_ROOT_PASSWORD: sree
          MYSQL_DATABASE: university

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
         npm install mysql
         npm install ts-node typescript --save-dev

      # Step 4: Wait for MySQL to be ready
      - name: Wait for MySQL
        run: |
          for i in {1..30}; do
            if mysqladmin ping -h 127.0.0.1 -u root -psree --silent; then
              echo "MySQL is ready!"
              break
            fi
            echo "Waiting for MySQL..."
            sleep 2
          done

      # Step 5: Initialize the database
      - name: Initialize database
        run: |
          mysql -h 127.0.0.1 -u root -psree university <<EOF
          CREATE TABLE EEngineeringStudents (
            Student_ID INT AUTO_INCREMENT PRIMARY KEY,
            Name VARCHAR(255),
            Age INT
          );
          INSERT INTO EEngineeringStudents (Name, Age) VALUES ('Alice', 22), ('Bob', 23);
          EOF

      # Step 6: Run the Node.js script
      - name: Run Node.js script
        run: ts-node typescript/mysql_connector_/mysql_connector_.ts
