name: MySQL Example Workflow

on:
  push:
    branches:
      - main

jobs:
  mysql-job:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost -u root --password=example --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
        env:
          MYSQL_ROOT_PASSWORD: example
          MYSQL_DATABASE: sample_db
          MYSQL_USER: sample_user
          MYSQL_PASSWORD: sample_password

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Wait for MySQL to be ready
        run: |
          echo "Waiting for MySQL to be ready..."
          for i in {1..30}; do
            if mysqladmin ping -h 127.0.0.1 -u root --password=example --silent; then
              echo "MySQL is ready!"
              break
            fi
            echo "Waiting for MySQL..."
            sleep 2
          done

      - name: Install MySQL client
        run: sudo apt-get update && sudo apt-get install -y mysql-client

      - name: Create a table and insert data
        run: |
          echo "Connecting to MySQL and creating a table..."
          mysql -h 127.0.0.1 -u sample_user -psample_password sample_db -e "
          CREATE TABLE IF NOT EXISTS users (
            id INT AUTO_INCREMENT PRIMARY KEY,
            name VARCHAR(255) NOT NULL,
            email VARCHAR(255) NOT NULL
          );
          INSERT INTO users (name, email) VALUES ('John Doe', 'john.doe@example.com');
          INSERT INTO users (name, email) VALUES ('Jane Smith', 'jane.smith@example.com');
          "

      - name: Query the database
        run: |
          echo "Querying the database..."
          mysql -h 127.0.0.1 -u sample_user -psample_password sample_db -e "
          SELECT * FROM users;
          "

      - name: Query the database from Python
        run: |
          python3 Python/mysql_connector_/mysql_connector_.py

