name: Robot Framework Web Tests

on:
    push:
      branches:
        - main
  

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install robotframework
        pip install robotframework-seleniumlibrary

    - name: Set up Chrome and ChromeDriver
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip curl
        CHROME_DRIVER_VERSION=$(curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE)
        wget -O /tmp/chromedriver.zip https://chromedriver.storage.googleapis.com/$CHROME_DRIVER_VERSION/chromedriver_linux64.zip
        unzip /tmp/chromedriver.zip -d /usr/local/bin/
        sudo apt-get install -y google-chrome-stable

    - name: Run Robot Framework tests
      run: |
        robot github_search_test.robot