name: Build and Run C++ Code in Docker with tmpfs

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create main.cpp file
      run: |
        echo '#include <iostream>' > main.cpp
        echo 'int main() {' >> main.cpp
        echo '    std::cout << "Hello, C++ World!" << std::endl;' >> main.cpp
        echo '    return 0;' >> main.cpp
        echo '}' >> main.cpp

    - name: Create Dockerfile
      run: |
        echo 'FROM gcc:latest' > Dockerfile
        echo 'RUN apt-get update && apt-get install -y bash' >> Dockerfile
        echo 'WORKDIR /usr/src/app' >> Dockerfile
        echo 'COPY entrypoint.sh /usr/local/bin/entrypoint.sh' >> Dockerfile
        echo 'RUN chmod +x /usr/local/bin/entrypoint.sh' >> Dockerfile
        echo 'ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]' >> Dockerfile

    - name: Create entrypoint.sh
      run: |
        echo '#!/bin/bash' > entrypoint.sh
        echo 'g++ -o /tmpfs/myapp /tmpfs/main.cpp' >> entrypoint.sh
        echo 'chmod +x /tmpfs/myapp' >> entrypoint.sh
        echo '/tmpfs/myapp' >> entrypoint.sh

    - name: Build Docker image
      run: docker build -t my-cpp-app .

    - name: Run Docker container with tmpfs
      run: docker run --tmpfs /tmpfs:rw,exec,size=64m -v $(pwd)/main.cpp:/tmpfs/main.cpp my-cpp-app

################################# ASSEMBLY #################################

    - name: Create Dockerfile
      run: |
            echo 'FROM debian:latest' > Dockerfile
            echo 'RUN apt-get update && apt-get install -y nasm binutils' >> Dockerfile
            echo 'WORKDIR /usr/src/app' >> Dockerfile
            echo 'COPY entrypoint.sh /usr/local/bin/entrypoint.sh' >> Dockerfile
            echo 'RUN chmod +x /usr/local/bin/entrypoint.sh' >> Dockerfile
            echo 'ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]' >> Dockerfile

    - name: Create entrypoint.sh
      run: |
            echo '#!/bin/bash' > entrypoint.sh
            echo 'mkdir -p /tmpfs' >> entrypoint.sh
            echo 'echo "section .data" > /tmpfs/example.asm' >> entrypoint.sh
            echo 'echo "    msg db \"Hello, Assembly World!\", 0" >> /tmpfs/example.asm' >> entrypoint.sh
            echo 'echo "section .text" >> /tmpfs/example.asm' >> entrypoint.sh
            echo 'echo "    global _start" >> /tmpfs/example.asm' >> entrypoint.sh
            echo 'echo "_start:" >> /tmpfs/example.asm' >> entrypoint.sh
            echo 'echo "    mov rax, 1" >> /tmpfs/example.asm' >> entrypoint.sh
            echo 'echo "    mov rdi, 1" >> /tmpfs/example.asm' >> entrypoint.sh
            echo 'echo "    mov rsi, msg" >> /tmpfs/example.asm' >> entrypoint.sh
            echo 'echo "    mov rdx, 21" >> /tmpfs/example.asm' >> entrypoint.sh  # Corrected the length of the message
            echo 'echo "    syscall" >> /tmpfs/example.asm' >> entrypoint.sh
            echo 'echo "    mov rax, 60" >> /tmpfs/example.asm' >> entrypoint.sh
            echo 'echo "    xor rdi, rdi" >> /tmpfs/example.asm' >> entrypoint.sh
            echo 'echo "    syscall" >> /tmpfs/example.asm' >> entrypoint.sh
            echo 'nasm -f elf64 /tmpfs/example.asm -o /tmpfs/example.o' >> entrypoint.sh
            echo 'ld /tmpfs/example.o -o /tmpfs/example' >> entrypoint.sh
            echo 'chmod +x /tmpfs/example' >> entrypoint.sh
            echo '/tmpfs/example' >> entrypoint.sh

    - name: Build Docker image
      run: docker build -t my-asm-app .

    - name: Run Docker container with tmpfs
      run: docker run --tmpfs /tmpfs:rw,exec,size=64m my-asm-app