name: Docker tmpfs Example

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create main.cpp file
      run: |
        echo '#include <iostream>' > main.cpp
        echo 'int main() {' >> main.cpp
        echo '    std::cout << "Hello, C++ World!" << std::endl;' >> main.cpp
        echo '    return 0;' >> main.cpp
        echo '}' >> main.cpp

    - name: Create Dockerfile
      run: |
        echo 'FROM gcc:latest' > Dockerfile
        echo 'WORKDIR /usr/src/app' >> Dockerfile
        echo 'COPY . .' >> Dockerfile
        echo 'RUN g++ -o myapp main.cpp' >> Dockerfile
        echo 'CMD ["./myapp"]' >> Dockerfile

    - name: Build Docker image
      run: docker build -t my-cpp-app .

    - name: Run Docker container
      run: docker run my-cpp-app