name: Spring Boot with Kotlin Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-run:
    name: Build and Run Spring Boot with Kotlin
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Step 3: Cache Maven dependencies
      - name: Cache Maven Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Step 4: Build the Spring Boot Application
      - name: Build Application
        run: |
          cd kotlin/spring_boot
          mvn clean package

      # Step 5: Run the Spring Boot Application
      - name: Run Application
        run: |
          cd kotlin/spring_boot
          nohup java -jar target/*.jar &
          sleep 10 # Allow the application to start

      # Step 6: Test the Application
      - name: Test Application with cURL
        run: |
          curl -X GET http://localhost:8080/hello?name=GitHubActions