name: Spring Boot with Kotlin Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-run:
    name: Build and Run Spring Boot with Kotlin
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Step 3: Cache Maven dependencies
      - name: Cache Maven Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Step 4: Build the Spring Boot Application
      - name: Build Application
        run: |
          cd kotlin/spring_boot
          mvn clean package

      # Step 5: Run the Spring Boot Application
      - name: Run Application
        run: |
          cd kotlin/spring_boot
          java -jar target/*.jar & 
          sleep 25 # Give the app a few seconds to start


      # Step 6: Test the Application
      - name: Test Application with cURL
        run: |
            curl -X GET http://localhost:8080/hello?name=GitHubActions

#       - name: Login to Docker Hub
#         uses: docker/login-action@v3
#         with:
#           username: ${{ secrets.DOCKERHUB_USERNAME }}
#           password: ${{ secrets.DOCKERHUB_TOKEN }}

#   # https://hub.docker.com/repository/docker/sreedockerhub19/news-search-service/general
#       - name: Build Docker image
#         run: docker build -t sreedockerhub19/my-spring-app:latest .

#       - name: Push Docker image to Docker Hub
#         run: docker push sreedockerhub19/my-spring-app:latest


##################################################################


# # To build and push docker image from Local to Docker hub:

# cd kotlin/spring_boot
# docker build -t my-spring-app .
# docker run -p 8080:8080 my-spring-app
# docker tag my-spring-app sreedockerhub19/my-spring-app:latest
# docker push sreedockerhub19/my-spring-app:latest
